<?php
// +----------------------------------------------------------------------
// | LotusAdmin
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://www.lotusadmin.top/ All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: wenhainan <qq 610176732>
// +----------------------------------------------------------------------
namespace  app\admin\controller;

use think\Db;
use think\Controller;
use think\Verify;
use app\admin\model\UserLog;

class Login extends  Controller
{

    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $module     = $this->request->module();
        if (!lotus_is_installed() && $module != 'install') {
            header('Location: ' . lotus_get_root() . 'index.php/?s=install');
            exit;
        }
    }
    //验证码
    public function getcode() {
        $length=4;
        if (isset($_GET['length']) && intval($_GET['length'])){
            $length = intval($_GET['length']);
        }

        //设置验证码字符库
        $code_set="";
        if(isset($_GET['charset'])){
            $code_set= trim($_GET['charset']);
        }

        $use_noise=1;
        if(isset($_GET['use_noise'])){
            $use_noise= intval($_GET['use_noise']);
        }

        $use_curve=1;
        if(isset($_GET['use_curve'])){
            $use_curve= intval($_GET['use_curve']);
        }

        $font_size=25;
        if (isset($_GET['font_size']) && intval($_GET['font_size'])){
            $font_size = intval($_GET['font_size']);
        }

        $width=0;
        if (isset($_GET['width']) && intval($_GET['width'])){
            $width = intval($_GET['width']);
        }

        $height=0;

        if (isset($_GET['height']) && intval($_GET['height'])){
            $height = intval($_GET['height']);
        }

        /* $background="";
        if (isset($_GET['background']) && trim(urldecode($_GET['background'])) && preg_match('/(^#[a-z0-9]{6}$)/im', trim(urldecode($_GET['background'])))){
            $background=trim(urldecode($_GET['background']));
        } */
        //TODO ADD Backgroud param!

        $config = array(
            'codeSet'   =>  !empty($code_set)?$code_set:"2345678abcdefhijkmnpqrstuvwxyzABCDEFGHJKLMNPQRTUVWXY",             // 验证码字符集合
            'expire'    =>  1800,            // 验证码过期时间（s）
            'useImgBg'  =>  false,           // 使用背景图片
            'fontSize'  =>  !empty($font_size)?$font_size:25,              // 验证码字体大小(px)
            'useCurve'  =>  $use_curve===0?false:true,           // 是否画混淆曲线
            'useNoise'  =>  $use_noise===0?false:true,            // 是否添加杂点
            'imageH'    =>  $height,               // 验证码图片高度
            'imageW'    =>  $width,               // 验证码图片宽度
            'length'    =>  !empty($length)?$length:4,               // 验证码位数
            'bg'        =>  array(243, 251, 254),  // 背景颜色
            'reset'     =>  true,           // 验证成功后是否重置
        );
        //ob_clean();
        $Verify = new \think\Verify($config);
        $Verify->entry();
    }

    //注册
    function register(){
        $request = $this->request;
        if($request->isPost()){
            $post = $request->post();
            $db = Db::name('user')
                ->where('username',$post['username'])
                ->find();
            if($db['id']>0){
                $this->error('别逗我，这个用户名被人注册了！');
            }
            $verify = new \think\Verify();
            $rlt = $verify->check($post['code'], "");
            if(!$rlt){
                $this->error('输入的验证码有误，请重试！');
            }
            $enterprise_code = md5(time());//企业代码
            $data= [
                'username' => $post['username'],
                'password' => md5($post['password']),
                'last_login_ip' => $this->request->ip(),
                'create_time' => date('Y-m-d h:i:s', time())
            ];
            Db::name('user')
                ->insert($data);
            $userId = Db::name('user')->getLastInsID();
            Db::name('auth_group_access')
                ->insert(['uid'=>$userId,'group_id'=>'228']);//指定企业管理员权限

            session('userid',$userId);
            //session('uid',$userId);
            session('username',$post['username']);
            UserLog::addLog([
                'uid'=>session('userid'),
                'name'=>'公司管理员注册',
                'url' => $this->request->path(),
                'ip' =>$this->request->ip()
            ]);
            $this->success('成功注册','admin/index/index');
        }else{
            $site_config = Db::name('system')
                ->where('name','site_config')
                ->value('value');
            $this->assign('site_config',unserialize($site_config));
            return $this->fetch('register');
        }

    }

    //登陆
    function login(){
        $request = $this->request;
        if($request->isPost()){
            $post = $request->post();
            $db = Db::name('user')->where('username',$post['username'])->find();
            if(empty($db['password'])){
                $this->error('别逗我,用户名不存在！');
            }
            $verify = new \think\Verify();
            $rlt = $verify->check($post['logincode'], "");
            if(!$rlt){
                $this->error('输入的验证码有误，请重试！');
            }
            if($db['shop']>0){
                $this->error('非后台管理用户，不允许登陆！');
            }
            if(md5($post['password'])!==$db['password']){
                $this->error('密码不正确');
            }else{
                if(array_key_exists('remember',$post)&&$post['remember']=='on'){
                    cookie('username',$post['username'],3600*24*7);
                    cookie('password',$post['password'],3600*24*7);
                }else{
                    $this->clearCookie();
                }
                //session('uid',$db['id']);
                session('userid',$db['id']);
                session('username',$db['username']);
                session('shop',$db['shop']);//店铺ID
                UserLog::addLog([
                    'uid'=>session('userid'),
                    'name'=>'登陆系统',
                    'url' => $this->request->path(),
                    'ip' =>$this->request->ip(),
                ]);
                //钩子
                $this->success('成功登陆','admin/index/index');
            }
        }else{
//            UserLog::addLog([
//                'uid'=>0,
//                'name'=>'访问登陆界面',
//                'url' => $this->request->path(),
//                'ip' =>$this->request->ip(),
//            ]);
            //加载系统配置
            $site_config = Db::name('system')
                ->where('name','site_config')
                ->value('value');
            $this->assign('site_config',unserialize($site_config));
            return $this->fetch();
        }

    }
    //清除cookie
    function clearCookie(){
        cookie('username',null);
        cookie('password',null);
        cookie(null, 'think_');
    }
    //注销
    function logout(){
        UserLog::addLog([
            'uid'=>session('userid'),
            'name'=>'注销系统',
            'url' => $this->request->path(),
            'ip' =>$this->request->ip(),
        ]);
        session('userid',null);
        session('username',null);
        session('shop',null);
        $this->success('注销中,前往登录页...','/admin/login/login');
    }
}